version: '3.1'

services:
  top-api-backend:
    image: top-api:latest
    container_name: top-api-backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
  mongo:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongo-data:/data/mongo
    ports:
      - "27017:27017"
